print("Hello World")
print("This is my first Python program!")
print("I am excited to learn Python programming.")  
print("Let's get started!")
print("Python is fun!") 
print("I can't wait to build more programs.")
print("Thank you for joining me on this journey!")  
print("Goodbye for now!")
print("See you next time!")
print("Stay curious and keep coding!")
print("Happy coding!")
print("End of the program.")
print("This is the final line of my first program.")
print("I hope you enjoyed it!") 
print("Until next time, happy coding!")
print("This marks the conclusion of my first Python script.")
print("Farewell, and keep exploring the world of programming!") 
print("Signing off from my first Python program.")
print("This is the last line of code in my first program.")
print("Thank you for being part of my coding journey!")
print("Goodbye and happy coding!")
print("This is the end of my first Python program.")
print("I look forward to writing more code in the future!")
print("This is the conclusion of my first Python script.")
print("Wishing you all the best in your coding adventures!")
print("This is the final output of my first program.")
print("Thank you for reading my first Python program!")
print("Goodbye and see you next time!")
print("This is the last statement in my first program.")
print("I hope you found it interesting!")